### ISSUE TITLE
Знакомство с Typescript

### ISSUE THREAD

**Issue by TorinAsakura** [atls-academy/Nikitabkv.github.io#3]
### С чем связан запрос на фичу?

Ознакомиться с азами работы с языками программирования на примере TypeScript, научиться покрывать простые кейсы по автоматизации задач с помощью ЯП и выполнить задание

### Расскажите как вы это себе видите

План
 - [x] Переменные и типы данных
 - [x] Структуры данных
 - [x] Условия
 - [x] Циклы
 - [x] Функции
 - [x] Работа с ошибками
 - [x] База Advanced JS API (методы массивов)
### Задание
Необходимо реализовать простой механизм авторизации. Должны быть удовлетворены следующие требования:

 - [x] Должны присутствовать функции для регистрации:
- `login(username, password)` - вход
- `logout()` - выход
- `register(username, password)` - регистрация
- `whoami()` - получение авторизованного на данный момент пользователя (сессии)
 - [x] При регистрации должна быть проверка: логин должен быть не короче 5 символов, пароль должен быть не короче 6. Если условие не выполняется - выбрасывать ошибку
 - [x] Должна быть возможность хранить креды (`credentials`) для нескольких пользователей
 - [x] При попытке сделать логаут без активной сессии - должна выбрасываться ошибка
 - [x] При попытке сделать `whoami` без активной сессии - выбрасывать ошибку
 - [x] При удачном вызове `whoami` в консоли должен быть вывод логина пользователя, который авторизован в данный момент
 - [x] При попытке сделать регистрацию/логин в момент, когда уже есть активная сессия - выбрасывать ошибку
 - [x] Все данные должны быть типизированы: аргументы функций, используемые переменные, возвращаемые функциями значения
#### Требования к обработке ошибок:

Ошибки (и код в целом) не должны содержать символов кириллицы, при этом в некоторых ошибках должны использоваться [шаблонные строки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals). Пример:

`User with login Dassfgfd not found`

`Password for user Johnathan is incorrect`

### Требования к оформлению задания
Задание должно быть выполнено в отдельной ветке. К этой ветке должен быть создан pull request. Если pull request еще не готов к мержу в мастер - он должен быть помечен как draft. Код должен удовлетворять проверкам lint и typecheck (`yarn lint`, `yarn typecheck`)

**Comment by TorinAsakura** [comment]
> Прошу помощь с **`yarn lint`**
> 
> Ошибка:
> 
> * `Error: No matching configuration found`
> 
> Терминал:
> 
> ```
> ┌ Lint
> │ auth/login.ts:0:0
> │ 
> │   Error: No matching configuration found for /home/nikita/WebstormProjects/Nikitabkv.github.io/auth/login.ts. 
> │   1 | import {IUser} from './user'
> │   2 |
> │   3 | let userData : IUser = {
> │ 
> │ auth/logout.ts:0:0
> │ 
> │   Error: No matching configuration found for /home/nikita/WebstormProjects/Nikitabkv.github.io/auth/logout.ts. 
> │   1 | import {IUser} from './user'
> │   2 |
> │   3 | let userData : IUser = {
> │ auth/register.ts:0:0
> ```
> 
> И по всем файлам задания, с функциями и интерфейсом, тоже самое
> 
> **`yarn typecheck`** проходит

https://github.com/atls-academy/jumpeebunee.github.io/issues/3#issuecomment-1550995194

**Comment by TorinAsakura** [comment]
> Запрашиваю помощь на создание пулл реквеста, а то я запутался с ними и лишнюю кнопку жмать боюсь
> 
> Тут всё верно? Не запушатся ли они сразу куда не надо? ![image](https://user-images.githubusercontent.com/108034376/239264338-684452f8-575e-4b59-8244-bd1e397604bb.png)

Пулл реквест ничего не пушит без нажатия на кнопку "merge". Я поставил запрет на пуш в мастер, можно не боятся

**Comment by Nikitabkv** [comment]
Я же могу закрыть задачу?

**Comment by TorinAsakura** [comment]
@Nikitabkv Давно должен был
