### ISSUE TITLE
Миграция на систему плагинов atls/tools

### ISSUE THREAD

**Issue by TorinAsakura** [atls-academy/Nikitabkv.github.io#6]
### Какого рода задача?
Мигрировать авторизацию на tools

###  Что и где будем менять?
Для сборки приложения необходимо использовать `yarn service build`, для запуска в дев режиме - `yarn service dev`

Необходимо оформить файл auth как пакет (воркспейс) с определенной структурой: директория `src` и `index.ts` внутри - [пример](https://github.com/atls/hyperion/blob/master/ui-parts/button/package.json)

Внутри package.json должны находится скрипты для запуска проекта - `build`, `dev` и `start`

- `build` билдит проект через `yarn service build` и кладет js в папку `dist`
- `dev` запускает проект в dev режиме
- `start` запускает уже сбилженный проект (`node dist/index.js`)

[Краткий обзор tools](https://github.com/atls/tools/wiki)

### Укажите референс
Приведение проекта к общему стеку

Пример приложения, собирающегося с помощью `yarn service` - https://github.com/atls/project-starter/blob/master/gateway/entrypoints/public/package.json

Пример библиотеки, которая будет публиковаться в npm регистр - https://github.com/atls/nextjs/blob/master/packages/next-sitemap-generator/package.json

**Comment by Nikitabkv** [comment]
**Ошибка**:  `Error: Can't resolve 'mock-aws-s3' in '/home/nikita/.yarn/berry/cache/@mapbox-node-pre-gyp-npm-1.0.10-1811160047-9.zip/node_modules/@mapbox/node-pre-gyp/lib/util'`

**Вопрос**: в какую сторону смотреть, в интернете перерыл уже очень много

**Скрин ошибки**:
![image](https://github.com/atls-academy/Nikitabkv.github.io/assets/108034376/bbeca98d-58c9-45f1-8c81-6e1982f3ca27)

tsconfig.json: 
```json
{
  "compilerOptions": {
    "lib": [
      "ESNext",
      "dom"
    ],
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "module": "esnext",
    "outDir": "./dist"
  },
  "include": ["auth/**/*"]
}
```
package.json
```json
{
  "name": "template",
  "private": true,
  "license": "BSD-3-Clause",
  "workspaces": [
    "auth"
  ],
  "devDependencies": {
    "@atls/code-service": "^0.0.18",
    "@atls/config-jest": "^0.0.5",
    "@atls/schematics": "^0.0.13",
    "@jest/core": "^29.5.0",
    "@types/bcrypt": "^5",
    "@types/eslint": "8",
    "@types/node": "20.1.3",
    "eslint": "8.18.0",
    "husky": "^8.0.3",
    "typescript": "4.9.5"
  },
  "dependencies": {
    "bcrypt": "^5.1.0"
  },
  "packageManager": "yarn@3.5.1"
}
```

**_auth_**/package.json
```json
{
  "name": "auth",
  "version": ".0.1",
  "license": "BSD-3-Clause",
  "main": "src/index.ts",
  "scripts": {
    "build": "yarn service build",
    "dev": "yarn service dev",
    "start": "node dist/index.js"
  },
  "dependencies": {
    "bcrypt": "^5.1.0"
  },
  "devDependencies": {
    "@types/bcrypt": "^5"
  }
}
```
Или лучше кинуть комит, чем описывать так?

**Comment by TorinAsakura** [comment]
@Nikitabkv Конечно коммититься лучше, это и в конвенции и в первых тасках было написано. Вопрос в другом - а как у тебя работают воркспейсы? И как они вообще работают? А работают ли? Посмотри в ярн.лок файл. Далее - поубивай зависимости по одной и посмотри изменится ли что-то, а ещё покажи-ка свой .yarnrc.yml…что-то тут не так…

**Comment by Nelfimov** [comment]
@Nikitabkv примерно твоя ошибка: https://stackoverflow.com/questions/72877801/bcrypt-crashing-node-modules

Как я вижу, корень проблемы - использование bcrypt вместо bcryptjs. К этому приводит ещё мысль описание пакета: https://www.npmjs.com/package/@mapbox/node-pre-gyp

**Comment by Nikitabkv** [comment]
> а ещё покажи-ка свой .yarnrc.yml…что-то тут не так…

```yml
yarnPath: .yarn/releases/yarn-0.0.1-git.20230217.hash-56aa982.cjs
```
Это всё

Закомичусь чуть позже, сначала попробую рекомендации все

**Comment by Nikitabkv** [comment]
По последним вопросам всё решилось

[В этом примере](https://github.com/atls/project-starter/blob/master/gateway/entrypoints/public/package.json), да и в остальных есть publishConfig, по нему вопрос, конкретно по: `"typings": "dist/index.d.ts"`
```json
{
  "publishConfig": {
    "access": "public",
    "main": "dist/index.js",
    -"typings": "dist/index.d.ts"
  }
}
```
Я так понимаю файл index.d.ts должен содержать типы для ts, но у меня генерируется только index.js и index.js.map
Что я упустил или куда-то не в ту степь пошел?
